// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -std=c++2d -triple x86_64-unknown-unknown -fpattern-matching -O0 -emit-llvm %s -o - | FileCheck %s

// CHECK-LABEL: define dso_local noundef i32 @_Z12char_patternc(
// CHECK-SAME: i8 noundef signext [[C:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_SELECT_RESULT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[MATCH_CASE_SELECTED:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[X:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store i8 [[C]], ptr [[C_ADDR]], align 1
// CHECK-NEXT:    store ptr [[C_ADDR]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
// CHECK-NEXT:    [[CONV:%.*]] = sext i8 [[TMP2]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[CONV]], 97
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_SELECT_ACTION:.*]], label %[[MATCH_SELECT_NEXT_PATTERN:.*]]
// CHECK:       [[MATCH_SELECT_ACTION]]:
// CHECK-NEXT:    store i32 1, ptr [[MATCH_SELECT_RESULT]], align 4
// CHECK-NEXT:    br label %[[MATCH_SELECT_END:.*]]
// CHECK:       [[MATCH_SELECT_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[TMP3]], align 1
// CHECK-NEXT:    [[CONV1:%.*]] = sext i8 [[TMP4]] to i32
// CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[CONV1]], 98
// CHECK-NEXT:    br i1 [[CMP2]], label %[[MATCH_SELECT_ACTION3:.*]], label %[[MATCH_SELECT_NEXT_PATTERN4:.*]]
// CHECK:       [[MATCH_SELECT_ACTION3]]:
// CHECK-NEXT:    store i32 2, ptr [[MATCH_SELECT_RESULT]], align 4
// CHECK-NEXT:    br label %[[MATCH_SELECT_END]]
// CHECK:       [[MATCH_SELECT_NEXT_PATTERN4]]:
// CHECK-NEXT:    br i1 true, label %[[MATCH_SELECT_INIT:.*]], label %[[MATCH_SELECT_NO_MATCH:.*]]
// CHECK:       [[MATCH_SELECT_INIT]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    store ptr [[TMP5]], ptr [[X]], align 8
// CHECK-NEXT:    br i1 true, label %[[MATCH_SELECT_ACTION5:.*]], label %[[MATCH_SELECT_GUARD_FAILED:.*]]
// CHECK:       [[MATCH_SELECT_ACTION5]]:
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[X]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[TMP6]], align 1
// CHECK-NEXT:    [[CONV6:%.*]] = sext i8 [[TMP7]] to i32
// CHECK-NEXT:    store i32 [[CONV6]], ptr [[MATCH_SELECT_RESULT]], align 4
// CHECK-NEXT:    store i1 true, ptr [[MATCH_CASE_SELECTED]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_CLEANUP:.*]]
// CHECK:       [[MATCH_SELECT_GUARD_FAILED]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_CASE_SELECTED]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_CLEANUP]]
// CHECK:       [[MATCH_SELECT_CLEANUP]]:
// CHECK-NEXT:    [[TMP8:%.*]] = load i1, ptr [[MATCH_CASE_SELECTED]], align 8
// CHECK-NEXT:    br i1 [[TMP8]], label %[[MATCH_SELECT_END]], label %[[MATCH_SELECT_NO_MATCH]]
// CHECK:       [[MATCH_SELECT_NO_MATCH]]:
// CHECK-NEXT:    call void @_ZSt9terminatev() #[[ATTR1:[0-9]+]]
// CHECK-NEXT:    unreachable
// CHECK:       [[MATCH_SELECT_END]]:
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[MATCH_SELECT_RESULT]], align 4
// CHECK-NEXT:    ret i32 [[TMP9]]
//
auto char_pattern(char c) {
  return c match {
    case 'a' => 1;
    case 'b' => 2;
    case auto&& x => int(x);
  };
}











// CHECK-LABEL: define dso_local void @_Z25test_void_returning_matchv(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[CLASS_ANON:%.*]], align 1
// CHECK-NEXT:    br i1 true, label %[[MATCH_SELECT_ACTION:.*]], label %[[MATCH_SELECT_END:.*]]
// CHECK:       [[MATCH_SELECT_ACTION]]:
// CHECK-NEXT:    call void @"_ZZ25test_void_returning_matchvENK3$_0clEv"(ptr noundef nonnull align 1 dereferenceable(1) [[REF_TMP]])
// CHECK-NEXT:    br label %[[MATCH_SELECT_END]]
// CHECK:       [[MATCH_SELECT_END]]:
// CHECK-NEXT:    ret void
//
void test_void_returning_match() {
  0 match { case _ => []() {}(); };
}

struct GuardInit {
  GuardInit();
  ~GuardInit();
  bool accept() const;
};

// CHECK-LABEL: define{{.*}} i32 @_Z20guard_init_statementi
// CHECK: match.select.init:
// CHECK: call void @_ZN9GuardInitC1Ev
// CHECK: call noundef zeroext i1 @_ZNK9GuardInit6acceptEv
// CHECK: match.select.action:
// CHECK: call void @_ZN9GuardInitD1Ev
// CHECK: ret i32
int guard_init_statement(int value) {
  return value match {
    case int copy if (GuardInit init; init.accept()) => copy;
    case _ => 0;
  };
}

// CHECK-LABEL: define dso_local void @_Z30test_match_if_without_bindingsbRi(
// CHECK-SAME: i1 noundef zeroext [[VALUE:%.*]], ptr noundef nonnull align 4 dereferenceable(4) [[RESULT:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[RESULT_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[VALUE]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[VALUE_ADDR]], align 1
// CHECK-NEXT:    store ptr [[RESULT]], ptr [[RESULT_ADDR]], align 8
// CHECK-NEXT:    store ptr [[VALUE_ADDR]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP2]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[LOADEDV]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[CONV]], 1
// CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[RESULT_ADDR]], align 8, !nonnull [[META1]], !align [[META2:![0-9]+]]
// CHECK-NEXT:    store i32 1, ptr [[TMP3]], align 4
// CHECK-NEXT:    br label %[[IF_END:.*]]
// CHECK:       [[IF_ELSE]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[RESULT_ADDR]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    store i32 2, ptr [[TMP4]], align 4
// CHECK-NEXT:    br label %[[IF_END]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    ret void
//
void test_match_if_without_bindings(bool value, int &result) {
  if (value match case true)
    result = 1;
  else
    result = 2;
}

// CHECK-LABEL: define dso_local noundef nonnull align 4 dereferenceable(4) ptr @_Z23select_lvalue_referencebRiS_(
// CHECK-SAME: i1 noundef zeroext [[FIRST:%.*]], ptr noundef nonnull align 4 dereferenceable(4) [[X:%.*]], ptr noundef nonnull align 4 dereferenceable(4) [[Y:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[FIRST_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_SELECT_REFRESULT:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[FIRST]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[FIRST_ADDR]], align 1
// CHECK-NEXT:    store ptr [[X]], ptr [[X_ADDR]], align 8
// CHECK-NEXT:    store ptr [[Y]], ptr [[Y_ADDR]], align 8
// CHECK-NEXT:    store ptr [[FIRST_ADDR]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP2]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[LOADEDV]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[CONV]], 1
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_SELECT_ACTION:.*]], label %[[MATCH_SELECT_NEXT_PATTERN:.*]]
// CHECK:       [[MATCH_SELECT_ACTION]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[X_ADDR]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[MATCH_SELECT_REFRESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_END:.*]]
// CHECK:       [[MATCH_SELECT_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP4]], align 1
// CHECK-NEXT:    [[LOADEDV1:%.*]] = icmp ne i8 [[TMP5]], 0
// CHECK-NEXT:    [[CONV2:%.*]] = zext i1 [[LOADEDV1]] to i32
// CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i32 [[CONV2]], 0
// CHECK-NEXT:    br i1 [[CMP3]], label %[[MATCH_SELECT_ACTION4:.*]], label %[[MATCH_SELECT_NO_MATCH:.*]]
// CHECK:       [[MATCH_SELECT_ACTION4]]:
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[MATCH_SELECT_REFRESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_END]]
// CHECK:       [[MATCH_SELECT_NO_MATCH]]:
// CHECK-NEXT:    call void @_ZSt9terminatev() #[[ATTR1]]
// CHECK-NEXT:    unreachable
// CHECK:       [[MATCH_SELECT_END]]:
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[MATCH_SELECT_REFRESULT]], align 8
// CHECK-NEXT:    ret ptr [[TMP7]]
//
int &select_lvalue_reference(bool first, int &x, int &y) {
  return first match -> int & {
    case true => x;
    case false => y;
  };
}


// CHECK-LABEL: define dso_local noundef nonnull align 4 dereferenceable(4) ptr @_Z23select_rvalue_referencebOiS_(
// CHECK-SAME: i1 noundef zeroext [[FIRST:%.*]], ptr noundef nonnull align 4 dereferenceable(4) [[X:%.*]], ptr noundef nonnull align 4 dereferenceable(4) [[Y:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[FIRST_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_SELECT_REFRESULT:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[FIRST]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[FIRST_ADDR]], align 1
// CHECK-NEXT:    store ptr [[X]], ptr [[X_ADDR]], align 8
// CHECK-NEXT:    store ptr [[Y]], ptr [[Y_ADDR]], align 8
// CHECK-NEXT:    store ptr [[FIRST_ADDR]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP2]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[LOADEDV]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[CONV]], 1
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_SELECT_ACTION:.*]], label %[[MATCH_SELECT_NEXT_PATTERN:.*]]
// CHECK:       [[MATCH_SELECT_ACTION]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[X_ADDR]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[MATCH_SELECT_REFRESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_END:.*]]
// CHECK:       [[MATCH_SELECT_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP4]], align 1
// CHECK-NEXT:    [[LOADEDV1:%.*]] = icmp ne i8 [[TMP5]], 0
// CHECK-NEXT:    [[CONV2:%.*]] = zext i1 [[LOADEDV1]] to i32
// CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i32 [[CONV2]], 0
// CHECK-NEXT:    br i1 [[CMP3]], label %[[MATCH_SELECT_ACTION4:.*]], label %[[MATCH_SELECT_NO_MATCH:.*]]
// CHECK:       [[MATCH_SELECT_ACTION4]]:
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[Y_ADDR]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[MATCH_SELECT_REFRESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_END]]
// CHECK:       [[MATCH_SELECT_NO_MATCH]]:
// CHECK-NEXT:    call void @_ZSt9terminatev() #[[ATTR1]]
// CHECK-NEXT:    unreachable
// CHECK:       [[MATCH_SELECT_END]]:
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[MATCH_SELECT_REFRESULT]], align 8
// CHECK-NEXT:    ret ptr [[TMP7]]
//
int &&select_rvalue_reference(bool first, int &&x, int &&y) {
  return first match -> int && {
    case true => static_cast<int &&>(x);
    case false => static_cast<int &&>(y);
  };
}


template <class T>
T &select_reference_template(bool first, T &x, T &y) {
  return first match -> decltype(auto) {
    case true => (x);
    case false => (y);
  };
}

template int &select_reference_template(bool, int &, int &);


// CHECK-LABEL: define dso_local noundef { double, double } @_Z14select_complexbCdS_(
// CHECK-SAME: i1 noundef zeroext [[FIRST:%.*]], double noundef [[X_COERCE0:%.*]], double noundef [[X_COERCE1:%.*]], double noundef [[Y_COERCE0:%.*]], double noundef [[Y_COERCE1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca { double, double }, align 8
// CHECK-NEXT:    [[X:%.*]] = alloca { double, double }, align 8
// CHECK-NEXT:    [[Y:%.*]] = alloca { double, double }, align 8
// CHECK-NEXT:    [[FIRST_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_SELECT_RESULT:%.*]] = alloca { double, double }, align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[X]], i32 0, i32 0
// CHECK-NEXT:    store double [[X_COERCE0]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[X]], i32 0, i32 1
// CHECK-NEXT:    store double [[X_COERCE1]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[Y]], i32 0, i32 0
// CHECK-NEXT:    store double [[Y_COERCE0]], ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[Y]], i32 0, i32 1
// CHECK-NEXT:    store double [[Y_COERCE1]], ptr [[TMP4]], align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[FIRST]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[FIRST_ADDR]], align 1
// CHECK-NEXT:    store ptr [[FIRST_ADDR]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP5]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP6]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[LOADEDV]] to i32
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[CONV]], 1
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_SELECT_ACTION:.*]], label %[[MATCH_SELECT_NEXT_PATTERN:.*]]
// CHECK:       [[MATCH_SELECT_ACTION]]:
// CHECK-NEXT:    [[X_REALP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[X]], i32 0, i32 0
// CHECK-NEXT:    [[X_REAL:%.*]] = load double, ptr [[X_REALP]], align 8
// CHECK-NEXT:    [[X_IMAGP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[X]], i32 0, i32 1
// CHECK-NEXT:    [[X_IMAG:%.*]] = load double, ptr [[X_IMAGP]], align 8
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_REALP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[MATCH_SELECT_RESULT]], i32 0, i32 0
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_IMAGP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[MATCH_SELECT_RESULT]], i32 0, i32 1
// CHECK-NEXT:    store double [[X_REAL]], ptr [[MATCH_SELECT_RESULT_REALP]], align 8
// CHECK-NEXT:    store double [[X_IMAG]], ptr [[MATCH_SELECT_RESULT_IMAGP]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_END:.*]]
// CHECK:       [[MATCH_SELECT_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP7]], align 1
// CHECK-NEXT:    [[LOADEDV1:%.*]] = icmp ne i8 [[TMP8]], 0
// CHECK-NEXT:    [[CONV2:%.*]] = zext i1 [[LOADEDV1]] to i32
// CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i32 [[CONV2]], 0
// CHECK-NEXT:    br i1 [[CMP3]], label %[[MATCH_SELECT_ACTION4:.*]], label %[[MATCH_SELECT_NO_MATCH:.*]]
// CHECK:       [[MATCH_SELECT_ACTION4]]:
// CHECK-NEXT:    [[Y_REALP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[Y]], i32 0, i32 0
// CHECK-NEXT:    [[Y_REAL:%.*]] = load double, ptr [[Y_REALP]], align 8
// CHECK-NEXT:    [[Y_IMAGP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[Y]], i32 0, i32 1
// CHECK-NEXT:    [[Y_IMAG:%.*]] = load double, ptr [[Y_IMAGP]], align 8
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_REALP5:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[MATCH_SELECT_RESULT]], i32 0, i32 0
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_IMAGP6:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[MATCH_SELECT_RESULT]], i32 0, i32 1
// CHECK-NEXT:    store double [[Y_REAL]], ptr [[MATCH_SELECT_RESULT_REALP5]], align 8
// CHECK-NEXT:    store double [[Y_IMAG]], ptr [[MATCH_SELECT_RESULT_IMAGP6]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_END]]
// CHECK:       [[MATCH_SELECT_NO_MATCH]]:
// CHECK-NEXT:    call void @_ZSt9terminatev() #[[ATTR1]]
// CHECK-NEXT:    unreachable
// CHECK:       [[MATCH_SELECT_END]]:
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_REALP7:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[MATCH_SELECT_RESULT]], i32 0, i32 0
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_REAL:%.*]] = load double, ptr [[MATCH_SELECT_RESULT_REALP7]], align 8
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_IMAGP8:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[MATCH_SELECT_RESULT]], i32 0, i32 1
// CHECK-NEXT:    [[MATCH_SELECT_RESULT_IMAG:%.*]] = load double, ptr [[MATCH_SELECT_RESULT_IMAGP8]], align 8
// CHECK-NEXT:    [[RETVAL_REALP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[RETVAL]], i32 0, i32 0
// CHECK-NEXT:    [[RETVAL_IMAGP:%.*]] = getelementptr inbounds nuw { double, double }, ptr [[RETVAL]], i32 0, i32 1
// CHECK-NEXT:    store double [[MATCH_SELECT_RESULT_REAL]], ptr [[RETVAL_REALP]], align 8
// CHECK-NEXT:    store double [[MATCH_SELECT_RESULT_IMAG]], ptr [[RETVAL_IMAGP]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = load { double, double }, ptr [[RETVAL]], align 8
// CHECK-NEXT:    ret { double, double } [[TMP9]]
//
_Complex double select_complex(bool first, _Complex double x,
                               _Complex double y) {
  return first match -> _Complex double {
    case true => x;
    case false => y;
  };
}

//.
// CHECK: [[META1]] = !{}
// CHECK: [[META2]] = !{i64 4}
//.
