// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --functions "extend|do_not_extend" --version 6
// RUN: %clang_cc1 -std=c++2d -triple x86_64-unknown-unknown -fpattern-matching -Wno-c++20-extensions -O0 -emit-llvm %s -o - | FileCheck %s

struct Lifetime {
//
  Lifetime(bool *_flag, int n) : flag(_flag), n(n) { *flag = true; }
//
  ~Lifetime() { *flag = false; }
  bool *flag;
  int n;
};

// CHECK-LABEL: define dso_local noundef zeroext i1 @_Z6extendi(
// CHECK-SAME: i32 noundef [[N:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i1, align 1
// CHECK-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[FLAG:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_LIFETIME:%.*]], align 8
// CHECK-NEXT:    [[MATCH_DECOMP_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP2:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP3:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[MATCH_RESULT_ADDR:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP4:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_TEST_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[B:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[CLEANUP_DEST_SLOT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// CHECK-NEXT:    store i8 0, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    call void @_ZN8LifetimeC1EPbi(ptr noundef nonnull align 8 dereferenceable(12) [[REF_TMP]], ptr noundef [[FLAG]], i32 noundef [[TMP5]])
// CHECK-NEXT:    store ptr [[REF_TMP]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1:![0-9]+]], !align [[META2:![0-9]+]]
// CHECK-NEXT:    store ptr [[TMP6]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[FLAG1:%.*]] = getelementptr inbounds nuw [[STRUCT_LIFETIME]], ptr [[TMP7]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[FLAG1]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP2]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[TMP9]], null
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[TOBOOL]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[TMP3]], align 1
// CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr [[TMP3]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP10]], 0
// CHECK-NEXT:    br i1 [[LOADEDV]], label %[[MATCH_PAT_TEST:.*]], label %[[MATCH_SUBJECT_FAIL:.*]]
// CHECK:       [[MATCH_PAT_TEST]]:
// CHECK-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP2]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP11]], align 8
// CHECK-NEXT:    store ptr [[TMP12]], ptr [[TMP4]], align 8
// CHECK-NEXT:    store i1 true, ptr [[MATCH_RESULT_ADDR]], align 8
// CHECK-NEXT:    br label %[[MATCH_RESULT:.*]]
// CHECK:       [[MATCH_SUBJECT_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_RESULT_ADDR]], align 8
// CHECK-NEXT:    br label %[[MATCH_RESULT]]
// CHECK:       [[MATCH_RESULT]]:
// CHECK-NEXT:    [[TMP13:%.*]] = load i1, ptr [[MATCH_RESULT_ADDR]], align 8
// CHECK-NEXT:    br i1 [[TMP13]], label %[[MATCH_DECOMP_NEXT_PATTERN:.*]], label %[[MATCH_DECOMP_FAIL:.*]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[N2:%.*]] = getelementptr inbounds nuw [[STRUCT_LIFETIME]], ptr [[TMP14]], i32 0, i32 1
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[N2]], align 8
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP15]], 101
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_DECOMP_NEXT_PATTERN3:.*]], label %[[MATCH_DECOMP_FAIL]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN3]]:
// CHECK-NEXT:    br label %[[MATCH_DECOMP_PASS:.*]]
// CHECK:       [[MATCH_DECOMP_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END:.*]]
// CHECK:       [[MATCH_DECOMP_PASS]]:
// CHECK-NEXT:    store i1 true, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END]]
// CHECK:       [[MATCH_DECOMP_END]]:
// CHECK-NEXT:    [[TMP16:%.*]] = load i1, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br i1 [[TMP16]], label %[[MATCH_TEST_INIT:.*]], label %[[MATCH_TEST_FAIL:.*]]
// CHECK:       [[MATCH_TEST_INIT]]:
// CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[TMP4]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    store ptr [[TMP17]], ptr [[B]], align 8
// CHECK-NEXT:    store i1 true, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_TEST_END:.*]]
// CHECK:       [[MATCH_TEST_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_TEST_END]]
// CHECK:       [[MATCH_TEST_END]]:
// CHECK-NEXT:    [[TMP18:%.*]] = load i1, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br i1 [[TMP18]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[B]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[TMP19]], align 1
// CHECK-NEXT:    [[LOADEDV4:%.*]] = icmp ne i8 [[TMP20]], 0
// CHECK-NEXT:    store i1 [[LOADEDV4]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP:.*]]
// CHECK:       [[IF_ELSE]]:
// CHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP21]], 202
// CHECK-NEXT:    br i1 [[CMP5]], label %[[IF_THEN6:.*]], label %[[IF_END:.*]]
// CHECK:       [[IF_THEN6]]:
// CHECK-NEXT:    [[TMP22:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV7:%.*]] = icmp ne i8 [[TMP22]], 0
// CHECK-NEXT:    store i1 [[LOADEDV7]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    br label %[[IF_END8:.*]]
// CHECK:       [[IF_END8]]:
// CHECK-NEXT:    store i32 0, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP]]
// CHECK:       [[CLEANUP]]:
// CHECK-NEXT:    call void @_ZN8LifetimeD1Ev(ptr noundef nonnull align 8 dead_on_return(12) dereferenceable(12) [[REF_TMP]]) #[[ATTR1:[0-9]+]]
// CHECK-NEXT:    [[CLEANUP_DEST:%.*]] = load i32, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    switch i32 [[CLEANUP_DEST]], label %[[UNREACHABLE:.*]] [
// CHECK-NEXT:      i32 0, label %[[CLEANUP_CONT:.*]]
// CHECK-NEXT:      i32 1, label %[[RETURN:.*]]
// CHECK-NEXT:    ]
// CHECK:       [[CLEANUP_CONT]]:
// CHECK-NEXT:    [[TMP23:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV9:%.*]] = icmp ne i8 [[TMP23]], 0
// CHECK-NEXT:    store i1 [[LOADEDV9]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN]]
// CHECK:       [[RETURN]]:
// CHECK-NEXT:    [[TMP24:%.*]] = load i1, ptr [[RETVAL]], align 1
// CHECK-NEXT:    ret i1 [[TMP24]]
// CHECK:       [[UNREACHABLE]]:
// CHECK-NEXT:    unreachable
//
bool extend(int n) {
  bool flag = false;
  if (Lifetime(&flag, n) match case [? auto&& b, 101]) {
    return b;
  } else if (n == 202) {
    return flag;
  }
  return flag;
}

// CHECK-LABEL: define dso_local noundef zeroext i1 @_Z13do_not_extendi(
// CHECK-SAME: i32 noundef [[N:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i1, align 1
// CHECK-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[FLAG:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[MATCH_DECOMP_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_LIFETIME:%.*]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP2:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[MATCH_RESULT_ADDR:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP3:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_TEST_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[B:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// CHECK-NEXT:    store i8 0, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    call void @_ZN8LifetimeC1EPbi(ptr noundef nonnull align 8 dereferenceable(12) [[REF_TMP]], ptr noundef [[FLAG]], i32 noundef [[TMP4]])
// CHECK-NEXT:    store ptr [[REF_TMP]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[FLAG1:%.*]] = getelementptr inbounds nuw [[STRUCT_LIFETIME]], ptr [[TMP5]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[FLAG1]], ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne ptr [[TMP7]], null
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[TOBOOL]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[TMP2]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP2]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP8]], 0
// CHECK-NEXT:    br i1 [[LOADEDV]], label %[[MATCH_PAT_TEST:.*]], label %[[MATCH_SUBJECT_FAIL:.*]]
// CHECK:       [[MATCH_PAT_TEST]]:
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-NEXT:    store ptr [[TMP10]], ptr [[TMP3]], align 8
// CHECK-NEXT:    store i1 true, ptr [[MATCH_RESULT_ADDR]], align 8
// CHECK-NEXT:    br label %[[MATCH_RESULT:.*]]
// CHECK:       [[MATCH_SUBJECT_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_RESULT_ADDR]], align 8
// CHECK-NEXT:    br label %[[MATCH_RESULT]]
// CHECK:       [[MATCH_RESULT]]:
// CHECK-NEXT:    [[TMP11:%.*]] = load i1, ptr [[MATCH_RESULT_ADDR]], align 8
// CHECK-NEXT:    br i1 [[TMP11]], label %[[MATCH_DECOMP_NEXT_PATTERN:.*]], label %[[MATCH_DECOMP_FAIL:.*]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[N2:%.*]] = getelementptr inbounds nuw [[STRUCT_LIFETIME]], ptr [[TMP12]], i32 0, i32 1
// CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[N2]], align 8
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP13]], 101
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_DECOMP_NEXT_PATTERN3:.*]], label %[[MATCH_DECOMP_FAIL]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN3]]:
// CHECK-NEXT:    br label %[[MATCH_DECOMP_PASS:.*]]
// CHECK:       [[MATCH_DECOMP_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END:.*]]
// CHECK:       [[MATCH_DECOMP_PASS]]:
// CHECK-NEXT:    store i1 true, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END]]
// CHECK:       [[MATCH_DECOMP_END]]:
// CHECK-NEXT:    [[TMP14:%.*]] = load i1, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br i1 [[TMP14]], label %[[MATCH_TEST_INIT:.*]], label %[[MATCH_TEST_FAIL:.*]]
// CHECK:       [[MATCH_TEST_INIT]]:
// CHECK-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP3]], align 8, !nonnull [[META1]]
// CHECK-NEXT:    store ptr [[TMP15]], ptr [[B]], align 8
// CHECK-NEXT:    store i1 true, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_TEST_END:.*]]
// CHECK:       [[MATCH_TEST_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_TEST_END]]
// CHECK:       [[MATCH_TEST_END]]:
// CHECK-NEXT:    [[TMP16:%.*]] = load i1, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    call void @_ZN8LifetimeD1Ev(ptr noundef nonnull align 8 dead_on_return(12) dereferenceable(12) [[REF_TMP]]) #[[ATTR1]]
// CHECK-NEXT:    br i1 [[TMP16]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV4:%.*]] = icmp ne i8 [[TMP17]], 0
// CHECK-NEXT:    store i1 [[LOADEDV4]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN:.*]]
// CHECK:       [[IF_ELSE]]:
// CHECK-NEXT:    [[TMP18:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP18]], 202
// CHECK-NEXT:    br i1 [[CMP5]], label %[[IF_THEN6:.*]], label %[[IF_END:.*]]
// CHECK:       [[IF_THEN6]]:
// CHECK-NEXT:    [[TMP19:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV7:%.*]] = icmp ne i8 [[TMP19]], 0
// CHECK-NEXT:    store i1 [[LOADEDV7]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    br label %[[IF_END8:.*]]
// CHECK:       [[IF_END8]]:
// CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV9:%.*]] = icmp ne i8 [[TMP20]], 0
// CHECK-NEXT:    store i1 [[LOADEDV9]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN]]
// CHECK:       [[RETURN]]:
// CHECK-NEXT:    [[TMP21:%.*]] = load i1, ptr [[RETVAL]], align 1
// CHECK-NEXT:    ret i1 [[TMP21]]
//
bool do_not_extend(int n) {
  bool flag = false;
  if ((Lifetime(&flag, n) match case [? auto&& b, 101])) {
    return flag;
  } else if (n == 202) {
    return flag;
  }
  return flag;
}
//.
// CHECK: [[META1]] = !{}
// CHECK: [[META2]] = !{i64 8}
//.
