// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -std=c++2d -triple x86_64-unknown-unknown -fpattern-matching -fcxx-exceptions -Wno-c++20-extensions -O0 -emit-llvm %s -o - | FileCheck %s

enum Color { Red, Blue };

struct S {
  Color color;
  int xs[2];
};

struct Result {
  Color color;
  int i;
  bool operator==(const Result&) const noexcept = default;
};

// CHECK-LABEL: define dso_local i64 @_Z28nested_decomposition_patternRK1S(
// CHECK-SAME: ptr noundef nonnull align 4 dereferenceable(12) [[S:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_RESULT:%.*]], align 4
// CHECK-NEXT:    [[S_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_SELECT_RESULT:%.*]] = alloca [[STRUCT_RESULT]], align 4
// CHECK-NEXT:    [[MATCH_DECOMP_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_DECOMP_RESULT1:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP2:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_CASE_SELECTED:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[C:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[S]], ptr [[S_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[S_ADDR]], align 8, !nonnull [[META1:![0-9]+]], !align [[META2:![0-9]+]]
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    store ptr [[TMP4]], ptr [[TMP1]], align 8
// CHECK-NEXT:    br i1 true, label %[[MATCH_DECOMP_NEXT_PATTERN:.*]], label %[[MATCH_DECOMP_FAIL7:.*]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[XS:%.*]] = getelementptr inbounds nuw [[STRUCT_S:%.*]], ptr [[TMP5]], i32 0, i32 1
// CHECK-NEXT:    store ptr [[XS]], ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[TMP2]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [2 x i32], ptr [[TMP6]], i64 0, i64 0
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP7]], 0
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_DECOMP_NEXT_PATTERN2:.*]], label %[[MATCH_DECOMP_FAIL:.*]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN2]]:
// CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP2]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [2 x i32], ptr [[TMP8]], i64 0, i64 1
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX3]], align 4
// CHECK-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP9]], 0
// CHECK-NEXT:    br i1 [[CMP4]], label %[[MATCH_DECOMP_NEXT_PATTERN5:.*]], label %[[MATCH_DECOMP_FAIL]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN5]]:
// CHECK-NEXT:    br label %[[MATCH_DECOMP_PASS:.*]]
// CHECK:       [[MATCH_DECOMP_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_DECOMP_RESULT1]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END:.*]]
// CHECK:       [[MATCH_DECOMP_PASS]]:
// CHECK-NEXT:    store i1 true, ptr [[MATCH_DECOMP_RESULT1]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END]]
// CHECK:       [[MATCH_DECOMP_END]]:
// CHECK-NEXT:    [[TMP10:%.*]] = load i1, ptr [[MATCH_DECOMP_RESULT1]], align 8
// CHECK-NEXT:    br i1 [[TMP10]], label %[[MATCH_DECOMP_NEXT_PATTERN6:.*]], label %[[MATCH_DECOMP_FAIL7]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN6]]:
// CHECK-NEXT:    br label %[[MATCH_DECOMP_PASS8:.*]]
// CHECK:       [[MATCH_DECOMP_FAIL7]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END9:.*]]
// CHECK:       [[MATCH_DECOMP_PASS8]]:
// CHECK-NEXT:    store i1 true, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END9]]
// CHECK:       [[MATCH_DECOMP_END9]]:
// CHECK-NEXT:    [[TMP11:%.*]] = load i1, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br i1 [[TMP11]], label %[[MATCH_SELECT_INIT:.*]], label %[[MATCH_SELECT_NEXT_PATTERN:.*]]
// CHECK:       [[MATCH_SELECT_INIT]]:
// CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[COLOR:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[TMP12]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[COLOR]], ptr [[C]], align 8
// CHECK-NEXT:    br i1 true, label %[[MATCH_SELECT_ACTION:.*]], label %[[MATCH_SELECT_GUARD_FAILED:.*]]
// CHECK:       [[MATCH_SELECT_ACTION]]:
// CHECK-NEXT:    [[COLOR10:%.*]] = getelementptr inbounds nuw [[STRUCT_RESULT]], ptr [[MATCH_SELECT_RESULT]], i32 0, i32 0
// CHECK-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[C]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[TMP13]], align 4
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[COLOR10]], align 4
// CHECK-NEXT:    [[I:%.*]] = getelementptr inbounds nuw [[STRUCT_RESULT]], ptr [[MATCH_SELECT_RESULT]], i32 0, i32 1
// CHECK-NEXT:    store i32 -1, ptr [[I]], align 4
// CHECK-NEXT:    store i1 true, ptr [[MATCH_CASE_SELECTED]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_CLEANUP:.*]]
// CHECK:       [[MATCH_SELECT_GUARD_FAILED]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_CASE_SELECTED]], align 8
// CHECK-NEXT:    br label %[[MATCH_SELECT_CLEANUP]]
// CHECK:       [[MATCH_SELECT_CLEANUP]]:
// CHECK-NEXT:    [[TMP15:%.*]] = load i1, ptr [[MATCH_CASE_SELECTED]], align 8
// CHECK-NEXT:    br i1 [[TMP15]], label %[[MATCH_SELECT_END:.*]], label %[[MATCH_SELECT_NEXT_PATTERN]]
// CHECK:       [[MATCH_SELECT_NEXT_PATTERN]]:
// CHECK-NEXT:    br i1 true, label %[[MATCH_SELECT_ACTION11:.*]], label %[[MATCH_SELECT_NO_MATCH:.*]]
// CHECK:       [[MATCH_SELECT_ACTION11]]:
// CHECK-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    store i32 0, ptr [[EXCEPTION]], align 16
// CHECK-NEXT:    call void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    unreachable
// CHECK:       [[THROW_CONT:.*:]]
// CHECK-NEXT:    br label %[[MATCH_SELECT_END]]
// CHECK:       [[MATCH_SELECT_NO_MATCH]]:
// CHECK-NEXT:    call void @_ZSt9terminatev() #[[ATTR3]]
// CHECK-NEXT:    unreachable
// CHECK:       [[MATCH_SELECT_END]]:
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[RETVAL]], ptr align 4 [[MATCH_SELECT_RESULT]], i64 8, i1 false)
// CHECK-NEXT:    [[TMP16:%.*]] = load i64, ptr [[RETVAL]], align 4
// CHECK-NEXT:    ret i64 [[TMP16]]
//
auto nested_decomposition_pattern(const S& s) {
  return s match -> Result {
    case [auto&& c, [0, 0]] => {c, -1};
    case _ => throw 0;
  };
}

//.
// CHECK: [[META1]] = !{}
// CHECK: [[META2]] = !{i64 4}
//.
