// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --functions "extend|do_not_extend" --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -std=c++2d -fpattern-matching -O0 -emit-llvm %s -o - | FileCheck %s

struct Lifetime {
//
  Lifetime(bool *_flag, int n) : flag(_flag), n(n) { *flag = true; }
//
  ~Lifetime() { *flag = false; }
  bool *flag;
  int n;
};

// CHECK-LABEL: define dso_local noundef zeroext i1 @_Z6extendi(
// CHECK-SAME: i32 noundef [[N:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i1, align 1
// CHECK-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[FLAG:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_LIFETIME:%.*]], align 8
// CHECK-NEXT:    [[MATCH_DECOMP_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH_TEST_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[B:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[CLEANUP_DEST_SLOT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// CHECK-NEXT:    store i8 0, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    call void @_ZN8LifetimeC1EPbi(ptr noundef nonnull align 8 dereferenceable(12) [[REF_TMP]], ptr noundef [[FLAG]], i32 noundef [[TMP2]])
// CHECK-NEXT:    store ptr [[REF_TMP]], ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1:![0-9]+]], !align [[META2:![0-9]+]]
// CHECK-NEXT:    store ptr [[TMP3]], ptr [[TMP1]], align 8
// CHECK-NEXT:    br i1 true, label %[[MATCH_DECOMP_NEXT_PATTERN:.*]], label %[[MATCH_DECOMP_FAIL:.*]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[N1:%.*]] = getelementptr inbounds nuw [[STRUCT_LIFETIME]], ptr [[TMP4]], i32 0, i32 1
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[N1]], align 8
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP5]], 101
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_DECOMP_NEXT_PATTERN2:.*]], label %[[MATCH_DECOMP_FAIL]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN2]]:
// CHECK-NEXT:    br label %[[MATCH_DECOMP_PASS:.*]]
// CHECK:       [[MATCH_DECOMP_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END:.*]]
// CHECK:       [[MATCH_DECOMP_PASS]]:
// CHECK-NEXT:    store i1 true, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END]]
// CHECK:       [[MATCH_DECOMP_END]]:
// CHECK-NEXT:    [[TMP6:%.*]] = load i1, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br i1 [[TMP6]], label %[[MATCH_TEST_INIT:.*]], label %[[MATCH_TEST_FAIL:.*]]
// CHECK:       [[MATCH_TEST_INIT]]:
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP1]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[FLAG3:%.*]] = getelementptr inbounds nuw [[STRUCT_LIFETIME]], ptr [[TMP7]], i32 0, i32 0
// CHECK-NEXT:    store ptr [[FLAG3]], ptr [[B]], align 8
// CHECK-NEXT:    store i1 true, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_TEST_END:.*]]
// CHECK:       [[MATCH_TEST_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_TEST_END]]
// CHECK:       [[MATCH_TEST_END]]:
// CHECK-NEXT:    [[TMP8:%.*]] = load i1, ptr [[MATCH_TEST_RESULT]], align 8
// CHECK-NEXT:    br i1 [[TMP8]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[B]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP10]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP11]], 0
// CHECK-NEXT:    store i1 [[LOADEDV]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP:.*]]
// CHECK:       [[IF_ELSE]]:
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP12]], 202
// CHECK-NEXT:    br i1 [[CMP4]], label %[[IF_THEN5:.*]], label %[[IF_END:.*]]
// CHECK:       [[IF_THEN5]]:
// CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV6:%.*]] = icmp ne i8 [[TMP13]], 0
// CHECK-NEXT:    store i1 [[LOADEDV6]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    br label %[[IF_END7:.*]]
// CHECK:       [[IF_END7]]:
// CHECK-NEXT:    store i32 0, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP]]
// CHECK:       [[CLEANUP]]:
// CHECK-NEXT:    call void @_ZN8LifetimeD1Ev(ptr noundef nonnull align 8 dead_on_return(12) dereferenceable(12) [[REF_TMP]]) #[[ATTR1:[0-9]+]]
// CHECK-NEXT:    [[CLEANUP_DEST:%.*]] = load i32, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    switch i32 [[CLEANUP_DEST]], label %[[UNREACHABLE:.*]] [
// CHECK-NEXT:      i32 0, label %[[CLEANUP_CONT:.*]]
// CHECK-NEXT:      i32 1, label %[[RETURN:.*]]
// CHECK-NEXT:    ]
// CHECK:       [[CLEANUP_CONT]]:
// CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV8:%.*]] = icmp ne i8 [[TMP14]], 0
// CHECK-NEXT:    store i1 [[LOADEDV8]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN]]
// CHECK:       [[RETURN]]:
// CHECK-NEXT:    [[TMP15:%.*]] = load i1, ptr [[RETVAL]], align 1
// CHECK-NEXT:    ret i1 [[TMP15]]
// CHECK:       [[UNREACHABLE]]:
// CHECK-NEXT:    unreachable
//
bool extend(int n) {
  bool flag = false;
  if (Lifetime(&flag, n) match case [auto&& b, 101]) {
    return *b;
  } else if (n == 202) {
    return flag;
  }
  return flag;
}

// CHECK-LABEL: define dso_local noundef zeroext i1 @_Z13do_not_extendi(
// CHECK-SAME: i32 noundef [[N:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i1, align 1
// CHECK-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[FLAG:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[MATCH_DECOMP_RESULT:%.*]] = alloca i1, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_LIFETIME:%.*]], align 8
// CHECK-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// CHECK-NEXT:    store i8 0, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    call void @_ZN8LifetimeC1EPbi(ptr noundef nonnull align 8 dereferenceable(12) [[REF_TMP]], ptr noundef [[FLAG]], i32 noundef [[TMP1]])
// CHECK-NEXT:    store ptr [[REF_TMP]], ptr [[TMP0]], align 8
// CHECK-NEXT:    br i1 true, label %[[MATCH_DECOMP_NEXT_PATTERN:.*]], label %[[MATCH_DECOMP_FAIL:.*]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[TMP0]], align 8, !nonnull [[META1]], !align [[META2]]
// CHECK-NEXT:    [[N1:%.*]] = getelementptr inbounds nuw [[STRUCT_LIFETIME]], ptr [[TMP2]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[N1]], align 8
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP3]], 101
// CHECK-NEXT:    br i1 [[CMP]], label %[[MATCH_DECOMP_NEXT_PATTERN2:.*]], label %[[MATCH_DECOMP_FAIL]]
// CHECK:       [[MATCH_DECOMP_NEXT_PATTERN2]]:
// CHECK-NEXT:    br label %[[MATCH_DECOMP_PASS:.*]]
// CHECK:       [[MATCH_DECOMP_FAIL]]:
// CHECK-NEXT:    store i1 false, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END:.*]]
// CHECK:       [[MATCH_DECOMP_PASS]]:
// CHECK-NEXT:    store i1 true, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    br label %[[MATCH_DECOMP_END]]
// CHECK:       [[MATCH_DECOMP_END]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i1, ptr [[MATCH_DECOMP_RESULT]], align 8
// CHECK-NEXT:    call void @_ZN8LifetimeD1Ev(ptr noundef nonnull align 8 dead_on_return(12) dereferenceable(12) [[REF_TMP]]) #[[ATTR1]]
// CHECK-NEXT:    br i1 [[TMP4]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP5]], 0
// CHECK-NEXT:    store i1 [[LOADEDV]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN:.*]]
// CHECK:       [[IF_ELSE]]:
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[N_ADDR]], align 4
// CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i32 [[TMP6]], 202
// CHECK-NEXT:    br i1 [[CMP3]], label %[[IF_THEN4:.*]], label %[[IF_END:.*]]
// CHECK:       [[IF_THEN4]]:
// CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV5:%.*]] = icmp ne i8 [[TMP7]], 0
// CHECK-NEXT:    store i1 [[LOADEDV5]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    br label %[[IF_END6:.*]]
// CHECK:       [[IF_END6]]:
// CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[FLAG]], align 1
// CHECK-NEXT:    [[LOADEDV7:%.*]] = icmp ne i8 [[TMP8]], 0
// CHECK-NEXT:    store i1 [[LOADEDV7]], ptr [[RETVAL]], align 1
// CHECK-NEXT:    br label %[[RETURN]]
// CHECK:       [[RETURN]]:
// CHECK-NEXT:    [[TMP9:%.*]] = load i1, ptr [[RETVAL]], align 1
// CHECK-NEXT:    ret i1 [[TMP9]]
//
bool do_not_extend(int n) {
  bool flag = false;
  if ((Lifetime(&flag, n) match case [_, 101])) {
    return flag;
  } else if (n == 202) {
    return flag;
  }
  return flag;
}
//.
// CHECK: [[META1]] = !{}
// CHECK: [[META2]] = !{i64 8}
//.
